ignored-vulnerabilities:
  # Insufficient validation of bracketed IPv6 hostnames in net/url
  # Found in: net/url@go1.23.12
  # Fixed in: net/url@go1.24.8
  - id: GO-2025-4010
    info: https://pkg.go.dev/vuln/GO-2025-4010
    silence-until: 2026-01-03