ignored-vulnerabilities:
    # Incorrect parsing of IPv6 host literals in net/url
    # Found in: net/url@go1.24.13
    # Fixed in: net/url@go1.25.8
    - id: GO-2026-4601
      silence-until: 2026-09-03
      info: https://pkg.go.dev/vuln/GO-2026-4601
    # Inefficient candidate hostname parsing in crypto/x509
    # Found in: crypto/x509@go1.24.13
    # Fixed in: crypto/x509@go1.25.11
    - id: GO-2026-5037
      silence-until: 2026-09-03
      info: https://pkg.go.dev/vuln/GO-2026-5037
