= ToolChain API


image:https://goreportcard.com/badge/github.com/codeready-toolchain/api[Go Report Card, link="https://goreportcard.com/report/github.com/codeready-toolchain/api"]
image:https://codecov.io/gh/codeready-toolchain/api/branch/master/graph/badge.svg[Codecov.io,link="https://codecov.io/gh/codeready-toolchain/api"]

== Building
Requires:

* Go version 1.14 - download for your development environment https://golang.org/dl/[here].

CodeReady ToolChain API is built using https://github.com/golang/go/wiki/Modules[Go modules].  Set the following environment variable in your CLI before building:

```sh
export GO111MODULE=on
```

To re-generate the `zz_generated.deepcopy.go` and `zz_generated.openapi.go` files as well as the CRD files, run the following command:

```sh
make generate
```

IMPORTANT: the codeready-toolchain repositories should be checked out under your GOPATH in order for the generation to generate files in the correct directories. eg. For this repository: `$GOPATH/src/github.com/codeready-toolchain/api`
NOTE: the `make generate` will generate the CRD files in the local `deploy/crds` directory and then dispatch the `.yaml` files in the `host-operator` and `member-operator` repositories, assuming they have been checked out and that *they are in a clean state*, meaning that they have no pending changes, besides previous versions of the CRD files.
