= Scripts
This directory contains a set of bash scripts that helps us with maintaining and managing OLM catalog files. The following part describes the purpose and functionality of all the script files.


== olm-setup.sh
The `olm-setup.sh` script is a collection of common functions used by other scripts. Executing this script on its own wouldn't do anything.


[#generate-deploy-hack]
== generate-deploy-hack.sh
The `generate-deploy-hack.sh` script generates the `deploy_csv.yaml` file containing two objects:

* `ConfigMap` containing all detected CSVs, CRDs and package file.
* `CatalogSource` that adds the operator into the OperatorHub and uses the `ConfigMap` as a source of operator bundle.

This `deploy_csv.yaml` file can be used for easy deployment of the operator in dev cluster as well as for testing purposes.
This script requires multiple parameters - see help for more information.


== olm-catalog-generate.sh
The `olm-catalog-generate.sh` script (re)generates OLM catalog files in their respective operator repositories/directories.
It generates:

* The operator bundle that is used as the base template for all next releases. Under the hood it runs the `operator-sdk` command with specific parameters.
* Some "hack" files, including:
 ** `deploy_csv.yaml` that helps with deploying the current version of the operator bundle to the cluster. It's the same file as is generated using <<generate-deploy-hack,generate-deploy-hack.sh>> script.
** `install_operator.yaml` that installs the operator using `OperatorGroup` and `Subscription` resources.

NOTE: The `olm-catalog-generate.sh` requires a single parameter, `--project-root`, and optionally the `--allnamespaces` param. It relies on `olm-setup.sh`.


== enrich-by-envs-from-yaml.sh
The `enrich-by-envs-from-yaml.sh` script takes two parameters:

1. path to CSV the deployment variables should be added to
2. path to an environment configuration file

If the provided environment configuration file exists then it transforms it into a list of key-value pairs.
The keys are generated by joining all YAML keys that are on the path to the value.
For example, with the following environment configuration:
```yaml
registration-service:
  environment: 'dev'
  replicas: 2
  auth-client:
    library-url: 'https://sso..../keycloak.js'
    public-keys-url: 'https://sso..../certs'
```
then the resulting list of key-value pairs would be:
``` yaml
REGISTRATION_SERVICE_ENV : 'dev'
REGISTRATION_SERVICE_REPLICAS : 2
REGISTRATION_SERVICE_AUTH_CLIENT_LIBRARY_URL : 'https://sso..../keycloak.js'
REGISTRATION_SERVICE_AUTH_CLIENT_PUBLIC_KEYS_URL : 'https://sso..../certs'
```
Once the key-value pairs have been generated, they are included in the CSV as additional environment parameters of the operator deployment.
The modified CSV is printed on the standard output.


== push-to-quay-nightly.sh
The `push-to-quay-nightly.sh` generates new operator bundles for every commit to master and pushes them to the "nightly" channel on https://quay.io[].
The simplified flow of the script is the following:

1. It calculates the version of the new CSV and of the previous one as well.
2. Using the `operator-sdk` it generates a new version of the operator bundle (for the "nightly" channel) using the base template that is stored in `<operator-repo>/deploy/olm-catalog/`.
 3. Replaces variables and parameters in the newly generated CSV.
 4. Uses `enrich-by-envs-from-yaml.sh` script to parse `<operator-repo>/deploy/env/prod.yaml` file (if exists) and to add additional deployment variables into the CSV.
 5. Gets the quay auth token - if the `QUAY_AUTH_TOKEN` variable is not provided, then it uses token taken from `~/.docker/config.json` file.
 6. Using the `operator-courier` binary pushes the new operator bundle into quay package(application).

The `push-to-quay-nightly.sh` requires only one parameter `--project-root` and accepts also `--operator-name`, `--embedded-repo` as well as `--quay-namespace`. Uses `olm-setup.sh` as its source.


== create-release-bundle.sh
The `create-release-bundle.sh` script creates an operator bundle of a given version in `<project-root>/manifests/` directory.
The simplified flow of the script looks like:

 1. Goes through all existing manifests in `<project-root>/manifests/` directory, detects the latest one (according to semVer) and takes its version.
 2. Using the `operator-sdk` it generates a new version of the operator bundle (for channel "alpha") from the base template that is stored in `<operator-repo>/deploy/olm-catalog/`.
 3. Replaces variables and parameters in the newly generated CSV.
 4. Uses `enrich-by-envs-from-yaml.sh` script to parse `<operator-repo>/deploy/env/prod.yaml` file (if exists) and to add additional deployment variables into the CSV.
 5. Stores the operator-bundle inside of the `<project-root>/manifests/` directory and modifies the package file.
 6. Using the `operator-courier` binary verifies the generated operator bundle.
 7. Generates the deploy hack file to make testing of the bundle easier.

The `create-release-bundle.sh` script doesn't push anything to quay yet - to do that please use the `push-to-quay-manifests.sh` script described below. 
NOTE: The `create-release-bundle.sh` script requires two parameters `--project-root` and `--next-version` and optionally `--operator-name`, `--embedded-repo` and `--quay-namespace`. It relies on `olm-setup.sh`.


== push-to-quay-manifest.sh
The `push-to-quay-manifest.sh` script takes the latest release manifest (according to semver) from the `<project-root>/manifests/` directory and pushes is to https://quay.io[].
NOTE: The script uses auth token taken either from `QUAY_AUTH_TOKEN` variable or from `~/.docker/config.json` file to upload the bundles.

NOTE: The script a single parameter `--project-root` and optionally `--operator-name`. It relies on `olm-setup.sh`.
